spring.application.name=GlobalMarketplace

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=${JWT_EXPIRATION_MS}
app.mail.from=${MAIL_FROM}
app.mail.name=${MAIL_NAME}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

server.port=${PORT:8080}

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.publishable.key=${STRIPE_PUBLISHABLE_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox
paypal.receiver.email=sb-xnh5350350750@business.example.com


mpesa.consumer.key=${MPESA_CONSUMER_KEY}
mpesa.consumer.secret=${MPESA_CONSUMER_SECRET}
mpesa.passkey=${MPESA_PASSKEY}
mpesa.shortcode=174379
mpesa.callback.url=${MPESA_CALLBACK_URL}
mpesa.base.url=https://sandbox.safaricom.co.ke

logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.zaxxer.hikari=DEBUG